apiVersion: v1
kind: Service
metadata:
  name: bob
spec:
  ports:
  - name: rpc
    port: 10009
    protocol: TCP
    targetPort: 10009
  - name: server
    port: 9735
    protocol: TCP
    targetPort: 9735
  selector:
    deployment: bob
